/**************************************************************************************************/
/**
 * @file moods.h
 * @author  generated by Utils/generate_moods.py
 * @brief  AUTO-GENERATED from Utils/moods.yaml -- DO NOT EDIT BY HAND.
 *         Edit Utils/moods.yaml and re-run the generator instead.
 *
 * @copyright Copyright (c) 2026
 *
 */
/**************************************************************************************************/

#ifndef MOODS_H
#define MOODS_H

/*------------------------------------------------------------------------------------------------*/
// HEADERS                                                                                        */
/*------------------------------------------------------------------------------------------------*/

#include <Arduino.h>

/*------------------------------------------------------------------------------------------------*/
// GLOBAL VARIABLES                                                                               */
/*------------------------------------------------------------------------------------------------*/

#define MOOD_COUNT          12
#define MAX_MOOD_COLOURS    4

/*------------------------------------------------------------------------------------------------*/
// CLASS DECLARATIONS                                                                             */
/*------------------------------------------------------------------------------------------------*/

enum Moods {
    IDLE,   // Default
    BLE_PROVISIONING,   // BLE Provisioning
    MOOD_1,   // Sad
    MOOD_2,   // Crying
    MOOD_3,   // Working
    MOOD_4,   // Happy
    MOOD_5,   // Leepy
    MOOD_6,   // Love
    MOOD_7,   // Cheeck Cheeck
    MOOD_8,   // Heepy
    MOOD_9,   // Angry
    MOOD_10   // Hungry
};

enum MoodPattern {
    PATTERN_SOLID,
    PATTERN_BLINK,
    PATTERN_BREATH,
    PATTERN_ALTERNATE,
    PATTERN_FADE
};

typedef struct {
    uint8_t     colours[MAX_MOOD_COLOURS][3]; // RGB values for each colour
    uint8_t     num_colours;
    MoodPattern pattern;
    uint16_t    period;
} MoodDefinition;

static const MoodDefinition MOOD_TABLE[MOOD_COUNT] = {
    { {{255, 200, 160}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}}, 1, PATTERN_BREATH, 6000 },   // IDLE Default
    { {{0, 255, 255}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}}, 1, PATTERN_BLINK, 1000 },   // BLE_PROVISIONING BLE Provisioning
    { {{0, 0, 160}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}}, 1, PATTERN_BREATH, 5000 },   // MOOD_1 Sad
    { {{0, 40, 180}, {0, 140, 200}, {0, 0, 0}, {0, 0, 0}}, 2, PATTERN_FADE, 2200 },   // MOOD_2 Crying
    { {{255, 255, 255}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}}, 1, PATTERN_SOLID, 0 },   // MOOD_3 Working
    { {{255, 205, 0}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}}, 1, PATTERN_SOLID, 0 },   // MOOD_4 Happy
    { {{50, 0, 110}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}}, 1, PATTERN_BREATH, 7000 },   // MOOD_5 Leepy
    { {{255, 30, 80}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}}, 1, PATTERN_BREATH, 1300 },   // MOOD_6 Love
    { {{255, 110, 140}, {255, 170, 190}, {0, 0, 0}, {0, 0, 0}}, 2, PATTERN_ALTERNATE, 600 },   // MOOD_7 Cheeck Cheeck
    { {{0, 210, 120}, {120, 230, 0}, {0, 0, 0}, {0, 0, 0}}, 2, PATTERN_ALTERNATE, 500 },   // MOOD_8 Heepy
    { {{255, 0, 0}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}}, 1, PATTERN_BLINK, 350 },   // MOOD_9 Angry
    { {{255, 110, 0}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}}, 1, PATTERN_BREATH, 2200 },   // MOOD_10 Hungry
};

/*------------------------------------------------------------------------------------------------*/
// FUNCTION DECLARATIONS                                                                          */
/*------------------------------------------------------------------------------------------------*/

// Look up a mood's definition. Out-of-range moods fall back to MOOD_TABLE[0].
static inline const MoodDefinition* get_mood_definition(Moods mood) {
    int i = (int)mood;
    if (i < 0 || i >= MOOD_COUNT) i = 0;
    return &MOOD_TABLE[i];
}

#endif // MOODS_H
