/**************************************************************************************************/
/**
 * @file moods.h
 * @author  generated by Utils/generate_moods.py
 * @brief  AUTO-GENERATED from Utils/moods.yaml -- DO NOT EDIT BY HAND.
 *         Edit Utils/moods.yaml and re-run the generator instead.
 *
 * @copyright Copyright (c) 2026
 *
 */
/**************************************************************************************************/

#ifndef MOODS_H
#define MOODS_H

/*------------------------------------------------------------------------------------------------*/
// HEADERS                                                                                        */
/*------------------------------------------------------------------------------------------------*/

#include <stdint.h>

/*------------------------------------------------------------------------------------------------*/
// GLOBAL VARIABLES                                                                               */
/*------------------------------------------------------------------------------------------------*/

#define MOOD_COUNT          14
#define MAX_MOOD_COLOURS    8

/*------------------------------------------------------------------------------------------------*/
// CLASS DECLARATIONS                                                                             */
/*------------------------------------------------------------------------------------------------*/

enum Moods {
    IDLE,   // Default
    BLE,   // BLE Provisioning
    NO_WIFI,   // No Wi-Fi
    MOOD_1,   // Excited
    MOOD_2,   // Happy
    MOOD_3,   // Sad
    MOOD_4,   // Upset
    MOOD_5,   // Anxious
    MOOD_6,   // Deep Breaths
    MOOD_7,   // Love
    MOOD_8,   // Heepy
    MOOD_9,   // Hungry
    MOOD_10,   // Tired
    MOOD_11   // Working
};

#define FIRST_SELECTABLE_MOOD MOOD_1

enum MoodPattern {
    PATTERN_SOLID,
    PATTERN_BLINK,
    PATTERN_BREATH,
    PATTERN_ALTERNATE,
    PATTERN_FADE,
    PATTERN_BREATH_ALTERNATE
};

typedef struct {
    uint8_t     colours[MAX_MOOD_COLOURS][3]; // RGB values for each colour
    uint8_t     num_colours;
    MoodPattern pattern;
    uint16_t    period;
} MoodDefinition;

static const MoodDefinition MOOD_TABLE[MOOD_COUNT] = {
    { {{255, 200, 160}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}}, 1, PATTERN_BREATH, 6000 },   // IDLE Default
    { {{0, 245, 255}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}}, 1, PATTERN_BLINK, 1000 },   // BLE BLE Provisioning
    { {{255, 90, 25}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}}, 1, PATTERN_BLINK, 500 },   // NO_WIFI No Wi-Fi
    { {{255, 220, 0}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}}, 1, PATTERN_BREATH, 1000 },   // MOOD_1 Excited
    { {{255, 0, 0}, {255, 110, 0}, {255, 220, 0}, {0, 200, 0}, {0, 90, 255}, {75, 0, 190}, {200, 0, 255}, {0, 0, 0}}, 7, PATTERN_FADE, 1000 },   // MOOD_2 Happy
    { {{0, 0, 100}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}}, 1, PATTERN_BREATH, 3000 },   // MOOD_3 Sad
    { {{130, 0, 0}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}}, 1, PATTERN_BREATH, 1000 },   // MOOD_4 Upset
    { {{40, 0, 60}, {100, 0, 150}, {180, 0, 255}, {200, 0, 50}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}}, 4, PATTERN_BREATH_ALTERNATE, 800 },   // MOOD_5 Anxious
    { {{20, 80, 10}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}}, 1, PATTERN_BREATH, 8000 },   // MOOD_6 Deep Breaths
    { {{150, 0, 60}, {255, 60, 120}, {255, 0, 140}, {200, 120, 255}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}}, 4, PATTERN_FADE, 1000 },   // MOOD_7 Love
    { {{255, 0, 150}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}}, 1, PATTERN_BLINK, 800 },   // MOOD_8 Heepy
    { {{110, 80, 0}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}}, 1, PATTERN_BREATH, 1000 },   // MOOD_9 Hungry
    { {{130, 0, 0}, {150, 55, 0}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}}, 2, PATTERN_FADE, 10000 },   // MOOD_10 Tired
    { {{240, 110, 0}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}}, 1, PATTERN_SOLID, 0 },   // MOOD_11 Working
};

/*------------------------------------------------------------------------------------------------*/
// FUNCTION DECLARATIONS                                                                          */
/*------------------------------------------------------------------------------------------------*/

// Look up a mood's definition. Out-of-range moods fall back to MOOD_TABLE[0].
static inline const MoodDefinition* get_mood_definition(Moods mood) {
    int i = (int)mood;
    if (i < 0 || i >= MOOD_COUNT) i = 0;
    return &MOOD_TABLE[i];
}

#endif // MOODS_H
