#!/usr/bin/env python3
"""
Generate Firmware/include/moods.h from Utils/moods.yaml.

moods.yaml is the single source of truth for every mood's colour(s) and pattern.
This script bakes it into a C header the firmware compiles against.

Usage:
    pip install pyyaml            # once
    python3 Utils/generate_moods.py
"""
import os
import sys

try:
    import yaml
except ImportError:
    sys.exit("PyYAML is not installed. Run:  pip install pyyaml")

HERE = os.path.dirname(os.path.abspath(__file__))          # .../Utils
ROOT = os.path.dirname(HERE)                                # repo root
YAML_PATH = os.path.join(HERE, "moods.yaml")
OUT_PATH = os.path.join(ROOT, "Firmware", "include", "moods.h")

MAX_MOOD_COLOURS = 4

# yaml keyword -> C enumerator. Enum is emitted in PATTERN_ORDER below.
PATTERN_MAP = {
    "solid": "PATTERN_SOLID",
    "blink": "PATTERN_BLINK",
    "breath": "PATTERN_BREATH",
    "alternate": "PATTERN_ALTERNATE",
    "fade": "PATTERN_FADE",
}
PATTERN_ORDER = ["PATTERN_SOLID", "PATTERN_BLINK", "PATTERN_BREATH",
                 "PATTERN_ALTERNATE", "PATTERN_FADE"]

WIDTH = 100


def rule():
    return "/*" + "-" * (WIDTH - 4) + "*/"


def section(label):
    return [rule(), ("// " + label).ljust(WIDTH - 2) + "*/", rule()]


def banner():
    star = "/*" + "*" * (WIDTH - 4) + "*/"
    return [
        star,
        "/**",
        " * @file moods.h",
        " * @author  generated by Utils/generate_moods.py",
        " * @brief  AUTO-GENERATED from Utils/moods.yaml -- DO NOT EDIT BY HAND.",
        " *         Edit Utils/moods.yaml and re-run the generator instead.",
        " *",
        " * @copyright Copyright (c) 2026",
        " *",
        " */",
        star,
    ]


def colour_literal(colours):
    padded = list(colours) + [[0, 0, 0]] * (MAX_MOOD_COLOURS - len(colours))
    return "{" + ", ".join("{%d, %d, %d}" % (c[0], c[1], c[2]) for c in padded) + "}"


def validate(moods):
    for m in moods:
        cols = m["colours"]
        if not (1 <= len(cols) <= MAX_MOOD_COLOURS):
            sys.exit(f"{m['id']}: {len(cols)} colours (must be 1..{MAX_MOOD_COLOURS})")
        for c in cols:
            if len(c) != 3 or any(not (0 <= v <= 255) for v in c):
                sys.exit(f"{m['id']}: bad colour {c} (need [R, G, B] each 0..255)")
        if m["pattern"] not in PATTERN_MAP:
            sys.exit(f"{m['id']}: unknown pattern '{m['pattern']}' "
                     f"(allowed: {list(PATTERN_MAP)})")
        if not (0 <= int(m["period"]) <= 65535):
            sys.exit(f"{m['id']}: period {m['period']} out of range (0..65535)")


def main():
    with open(YAML_PATH) as f:
        moods = yaml.safe_load(f)["moods"]
    validate(moods)

    L = banner()
    L += ["", "#ifndef MOODS_H", "#define MOODS_H", ""]

    L += section("HEADERS")
    L += ["", "#include <Arduino.h>", ""]

    L += section("GLOBAL VARIABLES")
    L += ["",
          f"#define MOOD_COUNT          {len(moods)}",
          f"#define MAX_MOOD_COLOURS    {MAX_MOOD_COLOURS}",
          ""]

    L += section("CLASS DECLARATIONS")
    L += [""]

    L += ["enum Moods {"]
    for i, m in enumerate(moods):
        comma = "," if i < len(moods) - 1 else ""
        L.append(f"    {m['id']}{comma}   // {m['name']}")
    L += ["};", ""]

    L += ["enum MoodPattern {"]
    for i, p in enumerate(PATTERN_ORDER):
        comma = "," if i < len(PATTERN_ORDER) - 1 else ""
        L.append(f"    {p}{comma}")
    L += ["};", ""]

    L += ["typedef struct {",
          "    uint8_t     colours[MAX_MOOD_COLOURS][3]; // RGB values for each colour",
          "    uint8_t     num_colours;",
          "    MoodPattern pattern;",
          "    uint16_t    period;",
          "} MoodDefinition;",
          ""]

    L += ["static const MoodDefinition MOOD_TABLE[MOOD_COUNT] = {"]
    for m in moods:
        L.append(f"    {{ {colour_literal(m['colours'])}, {len(m['colours'])}, "
                 f"{PATTERN_MAP[m['pattern']]}, {int(m['period'])} }},   "
                 f"// {m['id']} {m['name']}")
    L += ["};", ""]

    L += section("FUNCTION DECLARATIONS")
    L += ["",
          "// Look up a mood's definition. Out-of-range moods fall back to MOOD_TABLE[0].",
          "static inline const MoodDefinition* get_mood_definition(Moods mood) {",
          "    int i = (int)mood;",
          "    if (i < 0 || i >= MOOD_COUNT) i = 0;",
          "    return &MOOD_TABLE[i];",
          "}",
          ""]

    L += ["#endif // MOODS_H"]

    with open(OUT_PATH, "w") as f:
        f.write("\n".join(L) + "\n")
    print(f"Generated {OUT_PATH}  ({len(moods)} moods)")


if __name__ == "__main__":
    main()
